FROM redhat/ubi9-minimal:9.4

ARG UID=1001
RUN adduser -u $UID wgc 

ENV HOME=/app
WORKDIR $HOME

COPY target/wgc-embedded-server ./application

RUN chown $UID:0 . && \
    chmod 0775 . && \
    ls -la

USER $UID

EXPOSE 8080

ENV LOG4J_FORMAT_MSG_NO_LOOKUPS=true
ENTRYPOINT ["./application"]